plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id  'org.jetbrains.kotlin.kapt'
    id 'com.google.gms.google-services'
    id 'androidx.navigation.safeargs.kotlin'
}

android {
    namespace 'broz.tito.xrenovation.admin'
    compileSdk 34

    defaultConfig {
        applicationId "broz.tito.xrenovation.admin"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "0.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "MAPKIT_API_KEY", "\"${mapkitApiKey}\""
        buildConfigField "String", "FIREBASE_WEB_KEY", "\"${fireBaseWebKey}\""
        buildConfigField "String", "CAPTCHA_KEY", "\"${captchaKey}\""
        buildConfigField "String", "CAPTCHA_SERVER_KEY", "\"${captchaServerKey}\""
        buildConfigField "String", "PROJECT_ID", "\"${projectId}\""
    }

    buildFeatures {
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    ext {
        mapkitApiKey = getMapkitApiKey()
        fireBaseWebKey = getFireBaseWebKey()
        captchaKey = getCaptchaKey()
        captchaServerKey = getCaptchaServerKey()
        projectId = getProjectId()
    }
}


private String getMapkitApiKey() {
    def properties = new Properties()
    rootProject.file("local.properties").withInputStream {properties.load(it) }
    return properties.getProperty("MAPKIT_API_KEY", "")
}

private String getFireBaseWebKey() {
    def properties = new Properties()
    rootProject.file("local.properties").withInputStream {properties.load(it) }
    return properties.getProperty("FIREBASE_WEB_KEY", "")
}

private String getCaptchaKey() {
    def properties = new Properties()
    rootProject.file("local.properties").withInputStream {properties.load(it) }
    return properties.getProperty("CAPTCHA_KEY", "")
}

private String getCaptchaServerKey() {
    def properties = new Properties()
    rootProject.file("local.properties").withInputStream {properties.load(it) }
    return properties.getProperty("CAPTCHA_SERVER_KEY", "")
}

private String getProjectId() {
    def properties = new Properties()
    rootProject.file("local.properties").withInputStream {properties.load(it) }
    return properties.getProperty("PROJECT_ID", "")
}

dependencies {
    implementation 'com.google.firebase:firebase-database-ktx:21.0.0'
    implementation "com.google.firebase:firebase-appcheck:18.0.0"
    def nav_version = "2.7.7"
    kapt 'com.google.dagger:dagger-compiler:2.48'
    implementation 'com.google.dagger:dagger:2.48'
    implementation 'javax.inject:javax.inject:1'
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
    implementation 'com.yandex.android:maps.mobile:4.5.1-full'
    implementation 'com.squareup.retrofit2:retrofit:2.10.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'androidx.core:core-ktx:1.13.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.google.firebase:firebase-storage:20.3.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'com.github.leandroborgesferreira:loading-button-android:2.3.0'
    implementation 'com.mig35:carousellayoutmanager:1.4.6'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
